steps:
- name: 'gcr.io/cloud-builders/java/gradle'
  id: 'gradle'
  args: ['build','dockerImage']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/kdb-test/kdb-app', 'kdb-app/build/docker']
  waitFor: ['gradle']
images:
- gcr.io/$PROJECT_ID/kdb-test/kdb-app