steps:
- name: 'gcr.io/cloud-builders/java/gradle'
  id: 'gradle'
  args: ['build','dockerImage']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/kdb-test/qlsi-sim', 'qlsi-sim/build/docker']
  waitFor: ['gradle']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/kdb-test/qlsi-tp', 'qlsi-tp/build/docker']
  waitFor: ['gradle']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/kdb-test/qlsi-hdb', 'qlsi-hdb/build/docker']
  waitFor: ['gradle']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/kdb-test/python', 'python/build/docker']
  waitFor: ['gradle']
images:
- gcr.io/$PROJECT_ID/kdb-test/qlsi-sim
- gcr.io/$PROJECT_ID/kdb-test/qlsi-tp
- gcr.io/$PROJECT_ID/kdb-test/qlsi-hdb
- gcr.io/$PROJECT_ID/kdb-test/python
