# Block everything
{+block{Not Kubernetes}}
/

# except the external k8s endpoint, which we rewrite (see k8s-rewrite-external.filter)
{+client-header-filter{k8s-rewrite-external} -block{Kubernetes}}
CLUSTER_IP/
metadata.google.internal:80/