qlsData:([]
    time:`timespan$();
    sym:`$();
    cne:`$();
    corvilstream:`$();
    timestamp:`long$();
    clOrdID:();
    orderID:();
    quoteID:();
    senderCompID:`$();
    ccypair:`$();
    sendingTime:();
    mdReqID:();
    ordStatus:`$();
    execType:`$();
    msgType:`$();
    fixMsg:()
 );
